site_name: shad0wash's notebook 
site_url: https://note.shad0wash.cc/
repo_name: shadowash/notebook
repo_url: https://github.com/shadowash0215/notebook
site_description: shad0wash 的笔记本

theme: 
  name: 'material'
  language: 'zh'
  custom_dir: overrides
  icon: material/notebook-outline
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  font: false
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - footnotes
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - heti:
      extra_skipped_class:
        - arithmatex
  - statistics:
      page_check_metadata: comment
  - mathenv:
      tikzcd:
        enable: true
        cachefile: true

extra_javascript:
  # - javascripts/katex.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  - css/stylesheet.css

nav: 
- Home: 
  - 主页: index.md
  - 友链喵: links.md
- Computer Science:  
  - CSAPP: CSAPP.md
  - ASM: ASM.md
  - sys:
    - 计算机逻辑设计基础:
      - sys/fcl/index.md
      - 1 数据的表示和转换: sys/fcl/Lec1.md
      - 2 组合逻辑电路: sys/fcl/Lec2.md
  - fds:
    - fds/index.md
    - Mistakes Collection: fds/mistakes.md
    - 图: fds/graph.md
  
- Math:
  - math/index.md
  - AbstractAlgebra: 
    - math/AbstractAlgebra/index.md
    - Introduction: math/AbstractAlgebra/introduction.md
    - ChapterI:
      - math/AbstractAlgebra/ChapterI/index.md
      - 1.1 群定义 循环群: math/AbstractAlgebra/ChapterI/Lec1.md
      - 1.2 同态与同构 陪集 正规子群与商群: math/AbstractAlgebra/ChapterI/Lec2.md
      - 1.3 对称群 交错群 二面体群: math/AbstractAlgebra/ChapterI/Lec3.md
      - 1.4 阿贝尔群: math/AbstractAlgebra/ChapterI/Lec4.md
      - 1.5 群作用: math/AbstractAlgebra/ChapterI/Lec5.md
      - 1.6 Sylow 定理 有限群分类: math/AbstractAlgebra/ChapterI/Lec6.md
      - 1.7 幂零群和可解群 正规列和次正规列: math/AbstractAlgebra/ChapterI/Lec7.md
    - ChapterII:
      - math/AbstractAlgebra/ChapterII/index.md
      - 2.1 环基本定义: math/AbstractAlgebra/ChapterII/Lec1.md
      - 2.2 理想: math/AbstractAlgebra/ChapterII/Lec2.md
      - 2.3 交换环上的因子分解: math/AbstractAlgebra/ChapterII/Lec3.md
      - 2.4 分式环 局部化: math/AbstractAlgebra/ChapterII/Lec4.md
      - 2.5 多项式环 形式幂级数: math/AbstractAlgebra/ChapterII/Lec5.md
      - 2.6 多项式环上的分解: math/AbstractAlgebra/ChapterII/Lec6.md
    - ChapterIII:
      - math/AbstractAlgebra/ChapterIII/index.md
      - 3.1 模 模同态 正合列: math/AbstractAlgebra/ChapterIII/Lec1.md
      - 3.2 自由模和向量空间: math/AbstractAlgebra/ChapterIII/Lec2.md
      - 3.3 投射摸和内射模: math/AbstractAlgebra/ChapterIII/Lec3.md
      - 3.4 Hom 和 Tensor: math/AbstractAlgebra/ChapterIII/Lec4.md
      - 3.5 主理想整环上的有限生成模: math/AbstractAlgebra/ChapterIII/Lec5.md
    - ChapterIV:
      - math/AbstractAlgebra/ChapterIV/index.md
      - 4.1 域扩张: math/AbstractAlgebra/ChapterIV/Lec1.md
    - Homework archive: math/AbstractAlgebra/HW_archive.md
  - NumberTheory:
    - math/NumberTheory/index.md
    - 1 Euclidean Algorithm and Factorization: math/NumberTheory/Lec1.md
    - 2 Modular Arithmetic: math/NumberTheory/Lec2.md
    - 3 Some Diophantine Equations: math/NumberTheory/Lec3.md
    - 4 Order of units & Application in cryptography: math/NumberTheory/Lec4.md
    - 5 Sum of Two Squares: math/NumberTheory/Lec5.md
    - 6 Quadratic Reciprocity Law: math/NumberTheory/Lec6.md
    - 7 Sum of Four Squares:  math/NumberTheory/Lec7.md
    - 8 Quadratic Gauss Sum: math/NumberTheory/Lec8.md
    - 9 Pell's Equation: math/NumberTheory/Lec9.md
    - 10 Factorization in Quadratic Fields: math/NumberTheory/Lec10.md
    - 11 Primes of Arithmetic Progression: math/NumberTheory/Lec11.md
    - Homework archive: math/NumberTheory/HW_archive.md
  - DGC:
    - math/DGC/index.md
  
- Crypto: 
  - crypto/index.md
  - ECC: crypto/ECC.md
  - Lattice: crypto/Lattice.md