site_name: shad0wash's notebook 
site_url: https://note.shad0wash.cc/
repo_name: shadowash/notebook
repo_url: https://github.com/shadowash0215/notebook
site_description: shad0wash 的笔记本

theme: 
  name: 'material'
  language: 'zh'
  custom_dir: overrides
  icon: material/notebook-outline
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  font: false
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - footnotes
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - tikzautomata
  - heti:
      extra_skipped_class:
        - arithmatex
  - statistics:
      page_check_metadata: comment
  - mathenv:
      tikzcd:
        enable: true
        cachefile: true

extra_javascript:
  # - javascripts/katex.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  - css/stylesheet.css

nav: 
- Home: 
  - 主页: index.md
  - 友链喵: links.md
- Computer Science:  
  - CSAPP:
    - CSAPP/index.md
    - 1 计算机系统漫游: CSAPP/Chap1.md
    - 2 信息的表示和处理: CSAPP/Chap2.md
    - 3 程序的机器级表示: CSAPP/Chap3.md
  - fds:
    - fds/index.md
    - Mistakes Collection: fds/mistakes.md
    - 链表: fds/linkedlist.md
    - 栈和队列: fds/stack_queue.md
    - 树: fds/tree.md
    - 堆: fds/heap.md
    - 并查集: fds/union_find.md
    - 图: fds/graph.md
    - 排序: fds/sort.md
    - 哈希: fds/hash.md  
  - ads:
    - ads/index.md
    - AVL 树, Splay 树, 摊还分析: ads/Lec1.md
    - 红黑树, b+ 树: ads/Lec2.md
    - 左式堆, 斜堆: ads/Lec4.md
    - 动态规划: ads/Lec8.md
    - 贪心算法: ads/Lec9.md
    - $\mathsf{NP}$ 完全性: ads/Lec10.md
    - 近似算法: ads/Lec11.md
    - 局部搜索: ads/Lec12.md
- Math:
  - math/index.md
  - AbstractAlgebra: 
    - math/AbstractAlgebra/index.md
    - Introduction: math/AbstractAlgebra/introduction.md
    - ChapterI:
      - math/AbstractAlgebra/ChapterI/index.md
      - 1.1 群定义 循环群: math/AbstractAlgebra/ChapterI/Lec1.md
      - 1.2 同态与同构 陪集 正规子群与商群: math/AbstractAlgebra/ChapterI/Lec2.md
      - 1.3 对称群 交错群 二面体群: math/AbstractAlgebra/ChapterI/Lec3.md
      - 1.4 阿贝尔群: math/AbstractAlgebra/ChapterI/Lec4.md
      - 1.5 群作用: math/AbstractAlgebra/ChapterI/Lec5.md
      - 1.6 Sylow 定理 有限群分类: math/AbstractAlgebra/ChapterI/Lec6.md
      - 1.7 幂零群和可解群 正规列和次正规列: math/AbstractAlgebra/ChapterI/Lec7.md
    - ChapterII:
      - math/AbstractAlgebra/ChapterII/index.md
      - 2.1 环基本定义: math/AbstractAlgebra/ChapterII/Lec1.md
      - 2.2 理想: math/AbstractAlgebra/ChapterII/Lec2.md
      - 2.3 交换环上的因子分解: math/AbstractAlgebra/ChapterII/Lec3.md
      - 2.4 分式环 局部化: math/AbstractAlgebra/ChapterII/Lec4.md
      - 2.5 多项式环 形式幂级数: math/AbstractAlgebra/ChapterII/Lec5.md
      - 2.6 多项式环上的分解: math/AbstractAlgebra/ChapterII/Lec6.md
    - ChapterIII:
      - math/AbstractAlgebra/ChapterIII/index.md
      - 3.1 模 模同态 正合列: math/AbstractAlgebra/ChapterIII/Lec1.md
      - 3.2 自由模和向量空间: math/AbstractAlgebra/ChapterIII/Lec2.md
      - 3.3 投射摸和内射模: math/AbstractAlgebra/ChapterIII/Lec3.md
      - 3.4 Hom 和 Tensor: math/AbstractAlgebra/ChapterIII/Lec4.md
      - 3.5 主理想整环上的有限生成模: math/AbstractAlgebra/ChapterIII/Lec5.md
    - ChapterIV:
      - math/AbstractAlgebra/ChapterIV/index.md
      - 4.1 域扩张: math/AbstractAlgebra/ChapterIV/Lec1.md
      - 4.2 Galois 理论基本定理: math/AbstractAlgebra/ChapterIV/Lec2.md
    - Homework archive: math/AbstractAlgebra/HW_archive.md
    - Final Exam: math/AbstractAlgebra/Final.md
  - NumberTheory:
    - math/NumberTheory/index.md
    - 1 Euclidean Algorithm and Factorization: math/NumberTheory/Lec1.md
    - 2 Modular Arithmetic: math/NumberTheory/Lec2.md
    - 3 Some Diophantine Equations: math/NumberTheory/Lec3.md
    - 4 Order of units & Application in cryptography: math/NumberTheory/Lec4.md
    - 5 Sum of Two Squares: math/NumberTheory/Lec5.md
    - 6 Quadratic Reciprocity Law: math/NumberTheory/Lec6.md
    - 7 Sum of Four Squares:  math/NumberTheory/Lec7.md
    - 8 Quadratic Gauss Sum: math/NumberTheory/Lec8.md
    - 9 Pell's Equation: math/NumberTheory/Lec9.md
    - 10 Factorization in Quadratic Fields: math/NumberTheory/Lec10.md
    - 11 Primes of Arithmetic Progression: math/NumberTheory/Lec11.md
    - 12 Sum of Three Squares: math/NumberTheory/Lec12.md
    - 13 Congruent Number: math/NumberTheory/Lec13.md
    - Homework archive: math/NumberTheory/HW_archive.md
    - Final Exam: math/NumberTheory/Final.md
  - AlgebraicNumberTheory:
    - math/AlgebraicNumberTheory/index.md
    - 1 Integrality: math/AlgebraicNumberTheory/Lec1.md
    - 2 Norm, Trace, Discriminant: math/AlgebraicNumberTheory/Lec2.md
    - 3 Dedekind Domains: math/AlgebraicNumberTheory/Lec3.md
  - DGC:
    - math/DGC/index.md
  
- Crypto: 
  - crypto/index.md
  - ECC: crypto/ECC.md
  - Lattice: 
    - crypto/Lattice/index.md
    - 1 基本概念: crypto/Lattice/Lec1.md
  - RSA: 
    - crypto/RSA/index.md
    - Factor $N$ given $N$, $e$, $d$: crypto/RSA/Lec1.md