site_name: shadowash's notebook 
nav: 
- Home: index.md
- CSAPP: CSAPP.md
- ASM: ASM.md
theme: cyborg
repo_url: https://github.com/shadowash0215
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
